use SCOTT;
SELECT ENAME, JOB
FROM scott.EMP;

SELECT CONCAT(ENAME, '---', JOB)
FROM scott.EMP;

SELECT CONCAT(ENAME)
FROM scott.EMP;

SELECT GROUP_CONCAT(ENAME)
FROM scott.EMP;

SELECT GROUP_CONCAT(DISTINCT JOB)
FROM scott.EMP;
